import { enTranslations } from "@/content/en/index";

export const svTranslations: Record<keyof typeof enTranslations, string> = {
  'ServiceName': 'IQMED',
  'Settings': 'Inställningar',
  'Projects': 'Projekt',
  'Teams': 'Team',
  'Add team': 'Lägg till team',
  'Account Settings': 'Kontoinställningar',
  'Log out': 'Logga ut',
  'More': 'Mer',
  'View Project': 'Visa projekt',
  'Share Project': 'Dela projekt',
  'Delete Project': 'Ta bort projekt',
  'Dashboard': 'Dashboard',
  'Profile': 'Profil',
  'Users': 'Användare',
  'Page 1': 'Sida 1',
  'Page 2': 'Sida 2',
  'Failed to sign in with Google. Please try again.': 'Misslyckades att logga in med Google. Försök igen.',
  'Invalid email or password. Please check your credentials and try again.': 'Ogiltlig e-post eller lösenord. Kontrollera dina inloggningsuppgifter och försök igen.',
  'An error occurred during sign in. Please try again.': 'Ett fel uppstod under inloggning. Försök igen.',
  'An unexpected error occurred. Please try again.': 'Ett oväntat fel uppstod. Försök igen.',
  'Network error. Please check your connection and try again.': 'Nätverksfel. Kontrollera din anslutning och försök igen.',
  'Welcome back': 'Välkommen tillbaka',
  'Login with your Google account or email and password': 'Logga in med ditt Google-konto eller e-post och lösenord',
  'Login with Google': 'Logga in med Google',
  'Or continue with': 'Eller fortsätt med',
  'Email': 'E-post',
  'Password': 'Lösenord',
  'Forgot your password?': 'Glömt ditt lösenord?',
  'Signing in...': 'Loggar in...',
  'Login': 'Logga in',
  'Sign up': 'Registrera dig',
  'Don\'t have an account?': 'Har du inget konto?',
  'How do I optimize my company\'s tax situation?': 'Hur optimerar jag min företags skatteplats?',
  'My transactions': 'Mina transaktioner',
  'Invoices': 'Fakturor',
  'Offers': 'Offert',
  'Customers': 'Kunder',
  'Salaries': 'Löner',
  'Employees': 'Anställda',
  'Outlays': 'Utgifter',
  'Help': 'Hjälp',
  'Users who have been invited but haven\'t accepted yet': 'Användare som har blivit inbjudna men inte accepterat',
  'Please type \'delete\' to confirm': 'Vänligen skriv \'ta bort\' för att bekräfta',
  'Type \'delete\' here': 'Skriv \'ta bort\' här',
  'Information about your company\'s annual reporting status': 'Information om ditt företags årsredovisningsstatus',
  'Choose the plan that\'s right for you.': 'Välj den plan som passar dig.',
  'We\'ll sit on your desk.': 'Vi kommer att sitta på din skrivbord.',
  'Don\'t worry! You can still': 'Ingen fara! Du kan fortfarande',
  'Upgrade later when you\'re ready': 'Uppgradera senare när du är redo',
  'Manage your company\'s subscription and billing': 'Hantera din företags prenumeration och fakturering',
  'Your company\'s current subscription plan': 'Din företags nuvarande prenumerationsplan',
  'Update your workspace\'s basic information.': 'Uppdatera din workspace\'s grundläggande information.',
  'Update your workspace\'s contact information.': 'Uppdatera din workspace\'s kontaktinformation.',
  'Configure your workspace\'s accounting preferences.': 'Konfigurera din workspace\'s redovisningsinställningar.',
  'Workspace name doesn\'t match': 'Workspace-namn matchar inte',
  'Your workspace\'s current subscription plan': 'Din workspace\'s nuvarande prenumerationsplan',
  'Create Workspace': 'Skapa workspace',
  'Workspace': 'Workspace',
  'Workspaces': 'Workspace',
  'Your account is not connected to any workspaces': 'Din konto är inte anslutet till några workspace',
  'Please contact your administrator or support team': 'Kontakta din administratör eller supportteam',
  'No email address provided. Please try again with a valid email.': 'Ingen e-postadress angiven. Försök igen med en giltig e-postadress.',
  'User not found. Please contact your administrator to create an account.': 'Användaren hittades inte. Kontakta din administratör för att skapa ett konto.'} as const;

export default svTranslations;
