/* prettier-ignore */
export const svTranslations = {
  'ServiceName': 'Tibbna',
  'Settings': 'Inställningar',
  'Projects': 'Projekt',
  'Teams': 'Team',
  'Add team': 'Lägg till team',
  'Account Settings': 'Kontoinställningar',
  'Log out': 'Logga ut',
  'More': 'Mer',
  'View Project': 'Visa projekt',
  'Share Project': 'Dela projekt',
  'Delete Project': 'Ta bort projekt',
  'Dashboard': 'Dashboard',
  'Profile': 'Profil',
  'Users': 'Användare',
  'Page 1': 'Sida 1',
  'Page 2': 'Sida 2',
  'Create Workspace': 'Skapa workspace',
  'Workspace': 'Workspace',
  'Workspaces': 'Workspace',
  'Schedule': 'Schemalägg',
  'Patients': 'Patienter',
  'Patient List': 'Patientlista',
  'New Patient': 'Ny patient',
  'Search Patient': 'Sök patient',
  'Medical Records': 'Medicinallog',
  'View Records': 'Visa patientuppgifter',
  'Create Record': 'Skapa patientuppgifter',
  'Lab Results': 'Laboratorieresultat',
  'Prescriptions': 'Recept',
  'Write Prescription': 'Skriv recept',
  'Prescription History': 'Recepthistorik',
  'Drug Database': 'Läkemedelsdatabas',
  'Diagnostics': 'Diagnostik',
  'Order Tests': 'Beställ tester',
  'View Results': 'Visa resultat',
  'Imaging': 'Bildning',
  'Vital Signs': 'Vital Signer',
  'Medication Admin': 'Läkemedelsadministration',
  'Care Plans': 'Vårdplaner',
  'Active Plans': 'Aktiva planer',
  'Create Plan': 'Skapa plan',
  'Progress Notes': 'Förloppsposter',
  'Monitoring': 'Övervakning',
  'Patient Monitoring': 'Patientövervakning',
  'Alerts': 'Aviseringar',
  'Rounds': 'Rundor',
  'Appointments': 'Möten',
  'Today\'s Appointments': 'Dagens möten',
  'Schedule Appointment': 'Schemalägg möte',
  'Calendar View': 'Kalendervy',
  'Patient Registration': 'Patientregistrering',
  'Check-in': 'Check-in',
  'Billing': 'Fakturering',
  'Generate Invoice': 'Generera faktura',
  'Payment Processing': 'Betalningsbehandling',
  'Insurance Claims': 'Försäkringskrav',
  'Reports': 'Rapporter',
  'Daily Reports': 'Daglapporter',
  'Patient Flow': 'Patientflöde',
  'Revenue Reports': 'Intäktsrapporter',
  'Staff Management': 'Personalhantering',
  'Staff List': 'Personallista',
  'Schedules': 'Scheman',
  'Roles & Permissions': 'Roller & Behörigheter',
  'Department Management': 'Avdelningshantering',
  'Departments': 'Avdelningar',
  'Resources': 'Resurser',
  'Capacity Planning': 'Kapacitetsplanering',
  'Reports & Analytics': 'Rapporter & Analys',
  'Performance Metrics': 'Prestationsmått',
  'Financial Reports': 'Finansiella rapporter',
  'Quality Metrics': 'Kvalitetsmått',
  'Admin Panel': 'Adminpanel',
  'Lab Orders': 'Laboratoriebeställningar',
  'Pending Orders': 'Väntande beställningar',
  'In Progress': 'Pågående',
  'Completed': 'Slutförd',
  'Results Review': 'Resultatgranskning',
  'Pending Review': 'Väntande granskning',
  'Approved Results': 'Godkända resultat',
  'Critical Values': 'Kritiska värden',
  'Quality Control': 'Kvalitetskontroll',
  'QC Results': 'QC-resultat',
  'Calibration': 'Kalibrering',
  'Maintenance': 'Underhåll',
  'Sample Collection': 'Provtagning',
  'Collection Schedule': 'Provtagningsschema',
  'Sample Tracking': 'Provspårning',
  'Collection Guidelines': 'Provtagningsriktlinjer',
  'Patient Preparation': 'Patientförberedelse',
  'Pre-test Instructions': 'Förtestinstruktioner',
  'Patient Education': 'Patientutbildning',
  'Consent Forms': 'Samtyckesblankett',
  'Patient Communication': 'Patientkommunikation',
  'Lab Appointments': 'Laboratorietider',
  'Walk-in Queue': 'Drop-in-kö',
  'Sample Drop-off': 'Provlämning',
  'Register Patient': 'Registrera patient',
  'Update Information': 'Uppdatera information',
  'Insurance Verification': 'Försäkringsverifiering',
  'Billing & Reports': 'Fakturering & Rapporter',
  'Test Billing': 'Testfakturering',
  'Lab Management': 'Laboratoriehantering',
  'Equipment Status': 'Utrustningsstatus',
  'Inventory': 'Lager',
  'Workflow Optimization': 'Arbetsflödesoptimering',
  'Staff & Scheduling': 'Personal & Schemaläggning',
  'Shift Scheduling': 'Skiftschemaläggning',
  'Competency Tracking': 'Kompetensuppföljning',
  'Analytics': 'Analys',
  'Turnaround Times': 'Handläggningstider',
  'Test Volume': 'Testvolym',
  'Prescription Review': 'Receptgranskning',
  'Drug Interactions': 'Läkemedelsinteraktioner',
  'Clinical Guidelines': 'Kliniska riktlinjer',
  'Patient Consultation': 'Patientkonsultation',
  'Medication Counseling': 'Läkemedelsrådgivning',
  'Therapy Management': 'Terapihantering',
  'Adverse Events': 'Biverkningar',
  'Drug Information': 'Läkemedelsinformation',
  'Formulary': 'Läkemedelsförteckning',
  'Clinical Studies': 'Kliniska studier',
  'Medication Administration': 'Läkemedelsadministration',
  'Patient Medications': 'Patientläkemedel',
  'Administration Records': 'Administrationsregister',
  'Medication Reconciliation': 'Läkemedelsavstämning',
  'Medication Instructions': 'Läkemedelsinstruktioner',
  'Side Effects': 'Biverkningar',
  'Compliance Monitoring': 'Efterlevnadsövervakning',
  'Inventory Support': 'Lagerstöd',
  'Stock Levels': 'Lagernivåer',
  'Expiry Tracking': 'Utgångsdatumspårning',
  'Prescription Processing': 'Receptbehandling',
  'New Prescriptions': 'Nya recept',
  'Refills': 'Påfyllningar',
  'Customer Service': 'Kundservice',
  'Customer Registration': 'Kundregistrering',
  'Pickup Notifications': 'Upphämtningsmeddelanden',
  'Sales & Billing': 'Försäljning & Fakturering',
  'Point of Sale': 'Försäljningsställe',
  'Pharmacy Operations': 'Apoteksverksamhet',
  'Inventory Management': 'Lagerhantering',
  'Supplier Relations': 'Leverantörsrelationer',
  'Pharmacist Scheduling': 'Apotekarschemaläggning',
  'Technician Management': 'Teknikerhantering',
  'Training Records': 'Utbildningsregister',
  'Business Analytics': 'Affärsanalys',
  'Sales Analytics': 'Försäljningsanalys',
  'Prescription Trends': 'Recepttrender',
  'Hospital': 'Sjukhus',
  'Laboratory': 'Laboratorium',
  'Pharmacy': 'Apotek',
  'Theme': 'Tema',
  'Choose your preferred theme appearance': 'Välj ditt föredragna tema',
  'Language': 'Språk',
  'Select your preferred language': 'Välj ditt föredragna språk',
  'Your account is not connected to any workspaces': 'Din konto är inte anslutet till några workspace',
  'Please contact your administrator or support team': 'Kontakta din administratör eller supportteam',
  'No email address provided. Please try again with a valid email.': 'Ingen e-postadress angiven. Försök igen med en giltig e-postadress.',
  'User not found. Please contact your administrator to create an account.': 'Användaren hittades inte. Kontakta din administratör för att skapa ett konto.',
  'Invalid email or password. Please check your credentials and try again.': 'Ogiltlig e-post eller lösenord. Kontrollera dina inloggningsuppgifter och försök igen.',
  'Failed to sign in with Google. Please try again.': 'Misslyckades att logga in med Google. Försök igen.',
  'An error occurred during sign in. Please try again.': 'Ett fel uppstod under inloggning. Försök igen.',
  'An unexpected error occurred. Please try again.': 'Ett oväntat fel uppstod. Försök igen.',
  'Network error. Please check your connection and try again.': 'Nätverksfel. Kontrollera din anslutning och försök igen.',
  'Welcome back': 'Välkommen tillbaka',
  'Login with your Google account or email and password': 'Logga in med ditt Google-konto eller e-post och lösenord',
  'Login with Google': 'Logga in med Google',
  'Or continue with': 'Eller fortsätt med',
  'Email': 'E-post',
  'Password': 'Lösenord',
  'Forgot your password?': 'Glömt ditt lösenord?',
  'Signing in...': 'Loggar in...',
  'Login': 'Logga in',
  'Don\'t have an account?': 'Har du inget konto?',
  'Sign up': 'Registrera dig',
  'Help': 'Hjälp',
  'Compositions': 'Kompositioner',
  'EHR ID': 'EHR ID',
  'Add Encounter': 'Lägg till inspelning',
  'Failed to create encounter': 'Misslyckades att skapa inspelning',
  'Unknown error': 'Okänt fel',
  'Create a new clinical encounter for this EHR': 'Skapa en ny klinisk inspelning för detta EHR',
  'Basic Information': 'Grundinformation',
  'Composer Name': 'Kompositörnamn',
  'Enter composer name': 'Ange kompositörnamn',
  'Facility Name': 'Anläggningens namn',
  'Enter facility name': 'Ange anläggningens namn',
  'Start Time': 'Starttid',
  'Diagnosis': 'Diagnos',
  'Diagnosis Name': 'Diagnosnamn',
  'Enter diagnosis name': 'Ange diagnosnamn',
  'Clinical Description': 'Klinisk beskrivning',
  'Enter clinical description': 'Ange klinisk beskrivning',
  'Systolic BP': 'Systolisk blodtrycksmätning',
  'Diastolic BP': 'Diastolisk blodtrycksmätning',
  'Heart Rate': 'Hjärtfrekvens',
  'Body Temperature': 'Kroppstemperatur',
  'Respiratory Rate': 'Andningsfrekvens',
  'SpO2': 'SpO2',
  'Cancel': 'Avbryt',
  'Create Encounter': 'Skapa inspelning',
  // Add missing keys
  'All Appointments': 'Alla bokningar',
  'Patient Records': 'Patientjournaler',
  'Physicians': 'Läkare',
  'Physician List': 'Läkarlista',
  'Nurses': 'Sjuksköterskor',
  'Nurse List': 'Sjuksköterskelista',
  'Add Staff': 'Lägg till personal',
  'Edit Staff': 'Redigera personal',
  'Staff Details': 'Personalinformation',
  'Department List': 'Avdelningslista',
  'Add Department': 'Lägg till avdelning',
  'Edit Department': 'Redigera avdelning',
  'Department Details': 'Avdelningsinformation',
  'Operations': 'Operationer',
  'Operation List': 'Operationslista',
  'Schedule Operation': 'Boka operation',
  'Operation Details': 'Operationsinformation',
  'Facilities': 'Faciliteter',
  'Facility Management': 'Facilitetshantering',
  'Add Facility': 'Lägg till facilitet',
  'Edit Facility': 'Redigera facilitet',
  'Facility Details': 'Facilitetsinformation',
  'Add Lab Report': '',
  'Failed to create lab report': '',
  'Add Laboratory Report': '',
  'Create a new laboratory report for this EHR': '',
  'Enter laboratory name': '',
  'Report ID': '',
  'Enter report ID': '',
  'Report Time': '',
  'Test Method': '',
  'Enter test method': '',
  'Specimen Type': '',
  'e.g., Venous blood': '',
  'Test Events': '',
  'Add Test': '',
  'Test': '',
  'Test Name': '',
  'e.g., Complete Blood Count': '',
  'Test Status': '',
  'Select status': '',
  'Overall Interpretation': '',
  'Enter overall interpretation': '',
  'Test Results': '',
  'Add Result': '',
  'Result Name': '',
  'e.g., Hemoglobin': '',
  'Value': '',
  'Unit': '',
  'Interpretation': '',
  'Reference Range': '',
  'Create Report': '',
  'Lab': '',
  'Department': '',
  'All Departments': '',
  'Staff Assignment': '',
  'Insurance': '',
  'Insurance Plans': '',
  'Claims': '',
  'Verification': '',
  'Providers': '',
  'Invoices': '',
  'Payments': '',
  'Outstanding': '',
  'Add Physician': '',
  'Performance': '',
  'Orders': '',
  'Suppliers': '',
  'Lab Tests': '',
  'Results': '',
  'Equipment': ''} as const;

export default svTranslations;
