/**
 * Test Groups and Lab Types Configuration
 * Organized reference data for test reference ranges
 */

export const LAB_TYPES = [
  "Biochemistry",
  "Microbiology",
  "Histopathology",
] as const;

export const TEST_GROUPS = {
  // Biohemestry Groups
  Hormone: {
    name: "Hormone",
    labType: "Biochemistry",
    tests: [
      "TSH",
      "T3",
      "T4",
      "FT3",
      "FT4",
      "TG",
      "TGA",
      "ATPO",
      "TMA",
      "Rev T3",
      "TRAb",
      "T3 ut",
      "TBG",
      "FTI",
      "LH",
      "FSH",
      "PRL",
      "E2",
      "FE2",
      "PRG",
      "TEST",
      "FTEST",
      "β-HCG",
      "AMH",
      "Androg",
      "GA",
      "DHEA s",
      "Renin",
      "17-OHPROG",
      "ACTH",
      "Coritisol",
      "coritisol in urine",
      "PTH",
      "CT",
      "BGP",
      "VitD3",
      "GH",
      "C-P",
      "INS",
      "Pro-insulin",
      "IAA",
      "GAD65",
      "IGF-I",
      "FA",
      "VB12",
      "Fert",
      "MB",
      "Trop I",
      "Trop I",
      "ck-mb",
      "DD",
      "IR HOMA",
      "OGTT",
      "PTH",
      "CT",
      "BGP",
      "VitD3",
      "GH",
    ],
  },
  General: {
    name: "General",
    labType: "Biochemistry",
    tests: [
      "TSB",
      "DB",
      "ALT/GPT",
      "AST/GOT",
      "CHOL",
      "Trig",
      "HDL",
      "LDL",
      "Urea",
      "CRE",
      "UA",
      "Electrolyte (Na- K- Cl )",
      "Electrolyte(Na-k ca)",
      "Ca",
      "K",
      "Alp",
      "CU",
      "CPK-MB",
      "CPK",
      "GGT",
      "Fbs/Rbs",
      "HbA1c",
      "LA",
      "LDH",
      "MG",
      "u-albumin",
      "PO4",
      "ACP",
      "Fe",
      "TIBC",
      "Zn",
      "Alb",
      "GLOB",
      "TP",
      "AMY total",
      "LPS",
      "TCO2",
      "ABG",
      "Albumin creatinine ratio",
      "24 Hr. Urine for protein",
      "24 Hr. Urine for cortisol",
      "24 Hr. Urine for copper",
      "24 Hr. Urine for creatinine",
      "24 Hr. Urine for Amylase",
      "24 Hr. Urine for calcium",
      "24 Hr. Urine for chloride",
      "24 Hr. Urine for magnesium",
      "24 Hr. Urine for phousphorus",
      "24 Hr. Urine for potassium",
      "24 Hr. Urine for sodium",
      "24 Hr. Urine for uric acid",
      "24 Hr. Urine for oxalic acid",
      "24 Hr. Urine for Citrate",
      "micro albuminuria",
      "VMA",
      "Stone analysis",
      "Fructose for seminal fluid",
      "CrCL",
    ],
  },
  Serology: {
    name: "Serology",
    labType: "Biochemistry",
    tests: [
      "VDRL",
      "TPHA",
      "ASOT titer",
      "Pt",
      "Crp titer",
      "RF",
      "Rose bengal test",
      "TP",
      "Mo",
      "Typhoid IgM , IgG",
      "H.Pylori Ab",
      "H.pylori Ag",
    ],
  },
  Immunity: {
    name: "Immunity",
    labType: "Biochemistry",
    tests: [
      "ACL IgG",
      "ACL IgM",
      "APL IgG",
      "APL IgM",
      "Ttg IgG",
      "Ttg IgA",
      "AGA IgG",
      "AGA IgA",
      "IgE ( ELISA )",
      "IgE (COBAS E4)",
      "IgM",
      "IgG",
      "IgA",
      "TB",
      "AFP",
      "CEA",
      "CA 125",
      "CA 15-3",
      "CA 19-9",
      "PSA",
      "f-PSA",
      "Transferrin",
      "Beta 2GP IgM",
      "Beta 2GP IgG",
      "Anti-reticulum G",
      "Anti-reticulum G",
      "Anti- reticulum A",
      "Anti- reticulum A",
      "EMA IgG",
      "EMA IgA",
      "ALK",
      "Anti-SLA",
      "EBV IgG",
      "EBV IgM",
      "A1AT",
      "LPA",
      "APO A1",
      "APO B",
      "PAP",
      "PCT",
      "Calprotectin",
      "Lactoferrin",
      "Anti-CCP",
      "ENA",
      "ANA",
      "(igG)",
      "(igM)",
      "C3",
      "C4",
      "IHS",
    ],
  },
  Infectious_Disease: {
    name: "Infectious Disease",
    labType: "Biochemistry",
    tests: [
      "Toxo IgG",
      "Toxo IgM",
      "CMV IgG",
      "CMV IgM",
      "Rubella IgG",
      "Rubella IgM",
      "HSV 1/2 IgG",
      "HSV 1/2 IgM",
      "HBs Ag titer",
      "HBs Ag screen",
      "HBs Ab IgG",
      "Hbe Ag",
      "Hbe Ab IgG",
      "HBc Ab IgG",
      "(HBS Ag-Hbs Ab Hbe Ag - Hbe Ab -Hbc Ab )",
      "HCV IgG titer",
      "HCV screen",
      "HAV Titer",
      "HAV screen",
      "HEV screen",
      "HIV titer",
      "HIV screen",
    ],
  },
  Electrophoresis: {
    name: "Electrophoresis",
    labType: "Biochemistry",
    tests: [
      "Hb Electrophoresis HPLC",
      "HbA1 by HPLC",
      "SPE",
      "UPE",
      "Urine Bence Jones Protein Electrophoresis",
      "serum immune fixation",
      "Hb capillary's Electrophoresis",
      "HbA1c bycapillary's Electrophoresis",
    ],
  },
  //Polymerase Chain Reaction (PCR)
  PCR_Tests: {
    name: "Polymerase Chain Reaction",
    labType: "Biochemistry",
    tests: [
      "PCR For HCV Viral Load",
      "PCR For HBV Viral Load",
      "PCR for HIV viral load",
      "PCR For TB",
      "PCR For Human papilloma virus",
      "PCR For Geno Type HCV",
      "PCR For HCV Viral Load by  genexpert",
      "PCR For HBV Viral Load By genexpert",
      "PCR For TB By genexpert",
    ],
  },
  // Hematology Panels
  Hematology: {
    name: "Hematology",
    labType: "Biochemistry",
    tests: [
      "CBC",
      "ESR",
      "BF",
      "CBC-BF",
      "Retic",
      "Sickling test",
      "Malaria test",
      "PT &INR",
      "PTT",
      "FIB",
      "ABORH",
      "XMATCH",
      "WB",
      "PRBC",
      "FFP",
      "CRYO",
      "PLT",
      "PLT",
      "G6PD Titer",
      "G6PD Screen",
      "direct coomb test",
      "in direct coomb test",
      "Rh Ab titer",
      "AT3",
      "PROT-C",
      "PROT-S",
      "LE cell preparation",
      "Hemoglobin H preparation",
      "BT",
      "CT",
    ],
  },
  
  // Microbiology Groups
  MICROBIOLOGY_ABSCESS: {
    name: "Abscess Culture",
    labType: "Microbiology",
    tests: ["Culture & Sensitivity", "Gram Stain", "AFB Stain"],
  },
  MICROBIOLOGY_URINE: {
    name: "Urine Culture",
    labType: "Microbiology",
    tests: ["Urine Culture & Sensitivity", "Urine Microscopy"],
  },
  MICROBIOLOGY_STOOL: {
    name: "Stool Culture",
    labType: "Microbiology",
    tests: ["Stool Culture", "Ova & Parasites", "Occult Blood"],
  },
  MICROBIOLOGY_BLOOD: {
    name: "Blood Culture",
    labType: "Microbiology",
    tests: [
      "Blood Culture & Sensitivity",
      "Aerobic Culture",
      "Anaerobic Culture",
    ],
  },
  MICROBIOLOGY_SPUTUM: {
    name: "Sputum Culture",
    labType: "Microbiology",
    tests: ["Sputum Culture & Sensitivity", "AFB Culture", "Gram Stain"],
  },
  MICROBIOLOGY_WOUND: {
    name: "Wound Culture",
    labType: "Microbiology",
    tests: ["Wound Culture & Sensitivity", "Gram Stain"],
  },
  MICROBIOLOGY_NASAL: {
    name: "Nasal Swab",
    labType: "Microbiology",
    tests: ["Nasal Culture & Sensitivity", "MRSA Screen"],
  },
  MICROBIOLOGY_THROAT: {
    name: "Throat Swab",
    labType: "Microbiology",
    tests: ["Throat Culture & Sensitivity", "Strep Screen"],
  },
  MICROBIOLOGY_HVS: {
    name: "High Vaginal Swab",
    labType: "Microbiology",
    tests: ["HVS Culture & Sensitivity", "Candida Screen", "Trichomonas"],
  },
  MICROBIOLOGY_URETHRAL: {
    name: "Urethral Swab",
    labType: "Microbiology",
    tests: [
      "Urethral Culture & Sensitivity",
      "Gonorrhea Screen",
      "Chlamydia Screen",
    ],
  },
  MICROBIOLOGY_PLEURAL: {
    name: "Pleural Fluid",
    labType: "Microbiology",
    tests: ["Pleural Fluid Culture", "Cell Count", "Biochemistry", "Cytology"],
  },
  MICROBIOLOGY_ASCITIC: {
    name: "Ascitic Fluid",
    labType: "Microbiology",
    tests: ["Ascitic Fluid Culture", "Cell Count", "Albumin", "SAAG"],
  },
  MICROBIOLOGY_SYNOVIAL: {
    name: "Synovial Fluid",
    labType: "Microbiology",
    tests: ["Synovial Fluid Culture", "Cell Count", "Crystal Analysis"],
  },
  MICROBIOLOGY_CSF: {
    name: "Cerebro-Spinal Fluid",
    labType: "Microbiology",
    tests: ["CSF Culture", "Cell Count", "Protein", "Glucose", "Gram Stain"],
  },
  MICROBIOLOGY_SEMINAL: {
    name: "Seminal Fluid",
    labType: "Microbiology",
    tests: ["Semen Analysis", "Sperm Count", "Motility", "Morphology"],
  },
  MICROBIOLOGY_PERITONEAL: {
    name: "Peritoneal Fluid",
    labType: "Microbiology",
    tests: ["Peritoneal Fluid Culture", "Cell Count", "Biochemistry"],
  },
  // Histopathology Groups
  Histopathology_General: {
    name: "General",
    labType: "Histopathology",
    tests: [],
  },
} as const;

export type LabType = (typeof LAB_TYPES)[number];
export type TestGroupKey = keyof typeof TEST_GROUPS;

// Helper function to get all test groups for a specific lab type
export function getTestGroupsByLabType(labType: LabType) {
  return Object.entries(TEST_GROUPS)
    .filter(([_, group]) => group.labType === labType)
    .map(([key, group]) => ({
      key,
      name: group.name,
      tests: group.tests,
    }));
}

// Helper function to get all unique test group names
export function getAllTestGroupNames() {
  return Object.values(TEST_GROUPS).map((group) => group.name);
}
