/**
 * Seed Test Reference Ranges
 * Populates the database with comprehensive test reference data including:
 * - Age group specific ranges (NEO, PED, ADULT, ALL)
 * - Sex-specific ranges (M, F, ANY)
 * - Reference ranges and panic/critical values
 */

import { db } from "@/lib/db";
import { testReferenceRanges } from "@/lib/db/schema";

const WORKSPACE_ID = "fa9fb036-a7eb-49af-890c-54406dad139d"; // Using first workspace
const CREATED_BY = "5037145a-971e-4348-8e44-f7a7ca96a35f"; // Using rafel@alpeta.com as admin

const testReferenceData = [
  // HEMATOLOGY - CBC COMPONENTS
  {
    testcode: "HGB",
    testname: "Hemoglobin",
    category: "Hematology",
    unit: "g/dL",
    agegroup: "NEO",
    sex: "ANY",
    referencemin: 14.0,
    referencemax: 24.0,
    paniclow: 10.0,
    panichigh: 25.0,
  },
  {
    testcode: "HGB",
    testname: "Hemoglobin",
    category: "Hematology",
    unit: "g/dL",
    agegroup: "PED",
    sex: "ANY",
    referencemin: 11.0,
    referencemax: 14.5,
    paniclow: 7.0,
    panichigh: 20.0,
  },
  {
    testcode: "HGB",
    testname: "Hemoglobin",
    category: "Hematology",
    unit: "g/dL",
    agegroup: "ADULT",
    sex: "M",
    referencemin: 13.0,
    referencemax: 17.0,
    paniclow: 7.0,
    panichigh: 20.0,
  },
  {
    testcode: "HGB",
    testname: "Hemoglobin",
    category: "Hematology",
    unit: "g/dL",
    agegroup: "ADULT",
    sex: "F",
    referencemin: 11.5,
    referencemax: 15.5,
    paniclow: 7.0,
    panichigh: 20.0,
  },

  // WBC
  {
    testcode: "WBC",
    testname: "White Blood Cells",
    category: "Hematology",
    unit: "cells/µL",
    agegroup: "NEO",
    sex: "ANY",
    referencemin: 9000,
    referencemax: 30000,
    paniclow: 5000,
    panichigh: 50000,
  },
  {
    testcode: "WBC",
    testname: "White Blood Cells",
    category: "Hematology",
    unit: "cells/µL",
    agegroup: "PED",
    sex: "ANY",
    referencemin: 5000,
    referencemax: 15000,
    paniclow: 2000,
    panichigh: 30000,
  },
  {
    testcode: "WBC",
    testname: "White Blood Cells",
    category: "Hematology",
    unit: "cells/µL",
    agegroup: "ADULT",
    sex: "ANY",
    referencemin: 4000,
    referencemax: 11000,
    paniclow: 2000,
    panichigh: 30000,
  },

  // Platelets
  {
    testcode: "PLT",
    testname: "Platelets",
    category: "Hematology",
    unit: "cells/µL",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 150000,
    referencemax: 450000,
    paniclow: 20000,
    panichigh: 1000000,
  },

  // Hematocrit
  {
    testcode: "HCT",
    testname: "Hematocrit",
    category: "Hematology",
    unit: "%",
    agegroup: "ADULT",
    sex: "M",
    referencemin: 40,
    referencemax: 50,
    paniclow: 21,
    panichigh: 60,
  },
  {
    testcode: "HCT",
    testname: "Hematocrit",
    category: "Hematology",
    unit: "%",
    agegroup: "ADULT",
    sex: "F",
    referencemin: 36,
    referencemax: 46,
    paniclow: 21,
    panichigh: 60,
  },

  // RBC
  {
    testcode: "RBC",
    testname: "Red Blood Cells",
    category: "Hematology",
    unit: "million/µL",
    agegroup: "ADULT",
    sex: "M",
    referencemin: 4.4,
    referencemax: 5.9,
    paniclow: 2.5,
    panichigh: 7.0,
  },
  {
    testcode: "RBC",
    testname: "Red Blood Cells",
    category: "Hematology",
    unit: "million/µL",
    agegroup: "ADULT",
    sex: "F",
    referencemin: 3.9,
    referencemax: 5.1,
    paniclow: 2.5,
    panichigh: 7.0,
  },

  // ESR
  {
    testcode: "ESR",
    testname: "Erythrocyte Sedimentation Rate",
    category: "Hematology",
    unit: "mm/hr",
    agegroup: "ADULT",
    sex: "M",
    referencemin: 0,
    referencemax: 15,
    panichigh: 100,
  },
  {
    testcode: "ESR",
    testname: "Erythrocyte Sedimentation Rate",
    category: "Hematology",
    unit: "mm/hr",
    agegroup: "ADULT",
    sex: "F",
    referencemin: 0,
    referencemax: 20,
    panichigh: 100,
  },

  // Reticulocytes
  {
    testcode: "RETIC",
    testname: "Reticulocyte Count",
    category: "Hematology",
    unit: "%",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 0.5,
    referencemax: 2.5,
    panichigh: 10,
  },

  // COAGULATION
  {
    testcode: "PT",
    testname: "Prothrombin Time",
    category: "Hematology",
    unit: "seconds",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 11,
    referencemax: 13.5,
    panichigh: 25,
  },
  {
    testcode: "INR",
    testname: "International Normalized Ratio",
    category: "Hematology",
    unit: "ratio",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 0.8,
    referencemax: 1.2,
    panichigh: 5.0,
  },
  {
    testcode: "APTT",
    testname: "Activated Partial Thromboplastin Time",
    category: "Hematology",
    unit: "seconds",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 25,
    referencemax: 35,
    panichigh: 100,
  },
  {
    testcode: "BT",
    testname: "Bleeding Time",
    category: "Hematology",
    unit: "minutes",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 2,
    referencemax: 7,
    panichigh: 15,
  },
  {
    testcode: "CT",
    testname: "Clotting Time",
    category: "Hematology",
    unit: "minutes",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 5,
    referencemax: 10,
    panichigh: 20,
  },

  // BLOOD SMEAR / SPECIALIZED
  {
    testcode: "BLAST",
    testname: "Blasts",
    category: "Hematology",
    unit: "%",
    agegroup: "ALL",
    sex: "ANY",
    referencetext: "0% (Absent)",
    panictext: ">5%",
  },
  {
    testcode: "SICKLE",
    testname: "Sickle Cells",
    category: "Hematology",
    unit: "Present/Absent",
    agegroup: "ALL",
    sex: "ANY",
    referencetext: "Absent",
    panictext: "Present",
  },
  {
    testcode: "PARA",
    testname: "Blood Parasites",
    category: "Hematology",
    unit: "Present/Absent",
    agegroup: "ALL",
    sex: "ANY",
    referencetext: "Absent",
    panictext: "Present",
  },
  {
    testcode: "MALARIA",
    testname: "Malaria Parasite",
    category: "Hematology",
    unit: "Positive/Negative",
    agegroup: "ALL",
    sex: "ANY",
    referencetext: "Negative",
    panictext: "Positive",
  },
  {
    testcode: "MICROF",
    testname: "Microfilaria",
    category: "Hematology",
    unit: "Positive/Negative",
    agegroup: "ALL",
    sex: "ANY",
    referencetext: "Negative",
    panictext: "Positive",
  },
  {
    testcode: "BM-EXAM",
    testname: "Bone Marrow Examination",
    category: "Hematology",
    unit: "Descriptive",
    agegroup: "ALL",
    sex: "ANY",
    referencetext: "Normal",
    panictext: "Malignancy",
  },

  // ANEMIA WORKUP
  {
    testcode: "FERR",
    testname: "Ferritin",
    category: "Hematology",
    unit: "ng/mL",
    agegroup: "ADULT",
    sex: "M",
    referencemin: 30,
    referencemax: 400,
    panichigh: 1000,
  },
  {
    testcode: "FERR",
    testname: "Ferritin",
    category: "Hematology",
    unit: "ng/mL",
    agegroup: "ADULT",
    sex: "F",
    referencemin: 15,
    referencemax: 150,
    panichigh: 1000,
  },
  {
    testcode: "IRON",
    testname: "Serum Iron",
    category: "Hematology",
    unit: "µg/dL",
    agegroup: "ADULT",
    sex: "ANY",
    referencemin: 60,
    referencemax: 170,
    paniclow: 20,
  },
  {
    testcode: "B12",
    testname: "Vitamin B12",
    category: "Hematology",
    unit: "pg/mL",
    agegroup: "ADULT",
    sex: "ANY",
    referencemin: 200,
    referencemax: 900,
    paniclow: 100,
  },
  {
    testcode: "FOLATE",
    testname: "Folate",
    category: "Hematology",
    unit: "ng/mL",
    agegroup: "ADULT",
    sex: "ANY",
    referencemin: 2.7,
    referencemax: 17,
    paniclow: 1.0,
  },

  // BIOCHEMISTRY - ELECTROLYTES
  {
    testcode: "NA",
    testname: "Sodium",
    category: "Biochemistry",
    unit: "mEq/L",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 135,
    referencemax: 145,
    paniclow: 120,
    panichigh: 160,
  },
  {
    testcode: "K",
    testname: "Potassium",
    category: "Biochemistry",
    unit: "mEq/L",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 3.5,
    referencemax: 5.1,
    paniclow: 2.5,
    panichigh: 6.5,
  },
  {
    testcode: "CA",
    testname: "Calcium",
    category: "Biochemistry",
    unit: "mg/dL",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 8.4,
    referencemax: 10.2,
    paniclow: 6.5,
    panichigh: 13,
  },
  {
    testcode: "CL",
    testname: "Chloride",
    category: "Biochemistry",
    unit: "mEq/L",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 98,
    referencemax: 107,
    paniclow: 80,
    panichigh: 120,
  },
  {
    testcode: "HCO3",
    testname: "Bicarbonate",
    category: "Biochemistry",
    unit: "mEq/L",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 22,
    referencemax: 28,
    paniclow: 10,
    panichigh: 40,
  },

  // RENAL FUNCTION
  {
    testcode: "CREAT",
    testname: "Creatinine",
    category: "Biochemistry",
    unit: "mg/dL",
    agegroup: "ADULT",
    sex: "M",
    referencemin: 0.7,
    referencemax: 1.3,
    panichigh: 5.0,
  },
  {
    testcode: "CREAT",
    testname: "Creatinine",
    category: "Biochemistry",
    unit: "mg/dL",
    agegroup: "ADULT",
    sex: "F",
    referencemin: 0.6,
    referencemax: 1.1,
    panichigh: 5.0,
  },
  {
    testcode: "UREA",
    testname: "Urea/BUN",
    category: "Biochemistry",
    unit: "mg/dL",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 7,
    referencemax: 20,
    panichigh: 100,
  },
  {
    testcode: "EGFR",
    testname: "Estimated GFR",
    category: "Biochemistry",
    unit: "mL/min/1.73m²",
    agegroup: "ADULT",
    sex: "ANY",
    referencemin: 90,
    referencemax: 120,
    paniclow: 15,
  },

  // LIVER FUNCTION
  {
    testcode: "ALT",
    testname: "Alanine Aminotransferase",
    category: "Biochemistry",
    unit: "U/L",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 5,
    referencemax: 45,
    panichigh: 1000,
  },
  {
    testcode: "AST",
    testname: "Aspartate Aminotransferase",
    category: "Biochemistry",
    unit: "U/L",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 5,
    referencemax: 40,
    panichigh: 1000,
  },
  {
    testcode: "ALP",
    testname: "Alkaline Phosphatase",
    category: "Biochemistry",
    unit: "U/L",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 44,
    referencemax: 147,
    panichigh: 600,
  },
  {
    testcode: "GGT",
    testname: "Gamma-Glutamyl Transferase",
    category: "Biochemistry",
    unit: "U/L",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 8,
    referencemax: 61,
    panichigh: 500,
  },
  {
    testcode: "BILI",
    testname: "Bilirubin (Total)",
    category: "Biochemistry",
    unit: "mg/dL",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 0.2,
    referencemax: 1.2,
    panichigh: 10,
  },
  {
    testcode: "ALB",
    testname: "Albumin",
    category: "Biochemistry",
    unit: "g/dL",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 3.5,
    referencemax: 5.5,
    paniclow: 2.0,
  },
  {
    testcode: "LDH",
    testname: "Lactate Dehydrogenase",
    category: "Biochemistry",
    unit: "U/L",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 140,
    referencemax: 280,
    panichigh: 1000,
  },

  // GLUCOSE & LIPIDS
  {
    testcode: "GLU",
    testname: "Random Glucose",
    category: "Biochemistry",
    unit: "mg/dL",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 70,
    referencemax: 100,
    paniclow: 40,
    panichigh: 500,
  },
  {
    testcode: "FPG",
    testname: "Fasting Plasma Glucose",
    category: "Biochemistry",
    unit: "mg/dL",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 70,
    referencemax: 100,
    paniclow: 40,
    panichigh: 500,
  },
  {
    testcode: "OGTT",
    testname: "Oral Glucose Tolerance Test",
    category: "Biochemistry",
    unit: "mg/dL",
    agegroup: "ADULT",
    sex: "ANY",
    referencemin: 0,
    referencemax: 140,
    panichigh: 300,
  },
  {
    testcode: "HBA1C",
    testname: "Hemoglobin A1c",
    category: "Biochemistry",
    unit: "%",
    agegroup: "ADULT",
    sex: "ANY",
    referencemin: 4.0,
    referencemax: 5.6,
    panichigh: 12,
  },
  {
    testcode: "TRIG",
    testname: "Triglycerides",
    category: "Biochemistry",
    unit: "mg/dL",
    agegroup: "ADULT",
    sex: "ANY",
    referencemin: 0,
    referencemax: 150,
    panichigh: 1000,
  },
  {
    testcode: "HDL",
    testname: "HDL Cholesterol",
    category: "Biochemistry",
    unit: "mg/dL",
    agegroup: "ADULT",
    sex: "ANY",
    referencemin: 40,
    referencemax: 999,
  },
  {
    testcode: "LDL",
    testname: "LDL Cholesterol",
    category: "Biochemistry",
    unit: "mg/dL",
    agegroup: "ADULT",
    sex: "ANY",
    referencemin: 0,
    referencemax: 100,
  },

  // IMMUNOLOGY - INFECTION / VIRAL
  {
    testcode: "HBSAG",
    testname: "Hepatitis B Surface Antigen",
    category: "Immunology",
    unit: "Reactive/Non-reactive",
    agegroup: "ALL",
    sex: "ANY",
    referencetext: "Non-reactive",
    panictext: "Reactive",
  },
  {
    testcode: "ANTI-HCV",
    testname: "Anti-HCV",
    category: "Immunology",
    unit: "Reactive/Non-reactive",
    agegroup: "ALL",
    sex: "ANY",
    referencetext: "Non-reactive",
    panictext: "Reactive",
  },
  {
    testcode: "HIV",
    testname: "HIV Antibody",
    category: "Immunology",
    unit: "Reactive/Non-reactive",
    agegroup: "ALL",
    sex: "ANY",
    referencetext: "Non-reactive",
    panictext: "Reactive",
  },
  {
    testcode: "COVID-PCR",
    testname: "COVID-19 PCR",
    category: "Immunology",
    unit: "Detected/Not Detected",
    agegroup: "ALL",
    sex: "ANY",
    referencetext: "Not detected",
    panictext: "Detected",
  },
  {
    testcode: "VDRL",
    testname: "VDRL",
    category: "Immunology",
    unit: "Reactive/Non-reactive",
    agegroup: "ALL",
    sex: "ANY",
    referencetext: "Non-reactive",
    panictext: "Reactive",
  },

  // AUTOIMMUNE
  {
    testcode: "ANA",
    testname: "Antinuclear Antibody",
    category: "Immunology",
    unit: "titer",
    agegroup: "ALL",
    sex: "ANY",
    referencetext: "<1:40",
    panictext: "≥1:640",
  },
  {
    testcode: "DSDNA",
    testname: "Anti-dsDNA",
    category: "Immunology",
    unit: "IU/mL",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 0,
    referencemax: 25,
    panichigh: 200,
  },
  {
    testcode: "ANCA",
    testname: "ANCA",
    category: "Immunology",
    unit: "U/mL",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 0,
    referencemax: 20,
    panichigh: 100,
  },
  {
    testcode: "CRP",
    testname: "C-Reactive Protein",
    category: "Immunology",
    unit: "mg/L",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 0,
    referencemax: 5,
    panichigh: 100,
  },

  // TORCH
  {
    testcode: "TOXO",
    testname: "Toxoplasma IgG",
    category: "Immunology",
    unit: "IU/mL",
    agegroup: "ALL",
    sex: "ANY",
    referencetext: "<8 IU/mL",
    panictext: "Positive (pregnancy)",
  },
  {
    testcode: "RUBELLA",
    testname: "Rubella IgG",
    category: "Immunology",
    unit: "IU/mL",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 10,
    referencemax: 999,
    panictext: "Non-immune pregnancy",
  },
  {
    testcode: "CMV",
    testname: "Cytomegalovirus IgG",
    category: "Immunology",
    unit: "IU/mL",
    agegroup: "ALL",
    sex: "ANY",
    referencetext: "<6 IU/mL",
    panictext: "Acute positive",
  },
  {
    testcode: "HERPES",
    testname: "Herpes Simplex Virus",
    category: "Immunology",
    unit: "Index",
    agegroup: "ALL",
    sex: "ANY",
    referencetext: "<0.9",
    panictext: "Acute positive",
  },

  // TUMOR MARKERS
  {
    testcode: "CEA",
    testname: "Carcinoembryonic Antigen",
    category: "Immunology",
    unit: "ng/mL",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 0,
    referencemax: 3,
    panichigh: 20,
  },
  {
    testcode: "CA125",
    testname: "Cancer Antigen 125",
    category: "Immunology",
    unit: "U/mL",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 0,
    referencemax: 35,
    panichigh: 200,
  },
  {
    testcode: "CA199",
    testname: "Cancer Antigen 19-9",
    category: "Immunology",
    unit: "U/mL",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 0,
    referencemax: 37,
    panichigh: 1000,
  },

  // MICROBIOLOGY
  {
    testcode: "BACT",
    testname: "Blood Culture",
    category: "Microbiology",
    unit: "Growth/No Growth",
    agegroup: "ALL",
    sex: "ANY",
    referencetext: "No growth",
    panictext: "Growth",
  },
  {
    testcode: "CSF-CULT",
    testname: "CSF Culture",
    category: "Microbiology",
    unit: "Growth/No Growth",
    agegroup: "ALL",
    sex: "ANY",
    referencetext: "No growth",
    panictext: "Any growth",
  },
  {
    testcode: "UTI",
    testname: "Urine Culture",
    category: "Microbiology",
    unit: "CFU/mL",
    agegroup: "ALL",
    sex: "ANY",
    referencemin: 0,
    referencemax: 10000,
    panichigh: 100000,
  },
  {
    testcode: "PARA-ST",
    testname: "Stool Parasites",
    category: "Microbiology",
    unit: "Positive/Negative",
    agegroup: "ALL",
    sex: "ANY",
    referencetext: "Negative",
    panictext: "Positive",
  },
  {
    testcode: "C-DIFF",
    testname: "C. difficile",
    category: "Microbiology",
    unit: "Positive/Negative",
    agegroup: "ALL",
    sex: "ANY",
    referencetext: "Negative",
    panictext: "Positive",
  },
  {
    testcode: "TB-PCR",
    testname: "TB PCR",
    category: "Microbiology",
    unit: "Detected/Not Detected",
    agegroup: "ALL",
    sex: "ANY",
    referencetext: "Not detected",
    panictext: "Detected",
  },

  // HISTOPATHOLOGY / CYTOLOGY
  {
    testcode: "BIOPSY",
    testname: "Biopsy Examination",
    category: "Histopathology",
    unit: "Descriptive",
    agegroup: "ALL",
    sex: "ANY",
    referencetext: "Benign",
    panictext: "Malignancy",
  },
  {
    testcode: "FNAC",
    testname: "Fine Needle Aspiration Cytology",
    category: "Histopathology",
    unit: "Descriptive",
    agegroup: "ALL",
    sex: "ANY",
    referencetext: "Benign",
    panictext: "Malignant",
  },
  {
    testcode: "PAP",
    testname: "Pap Smear",
    category: "Histopathology",
    unit: "Classification",
    agegroup: "ALL",
    sex: "F",
    referencetext: "NILM",
    panictext: "HSIL / Cancer",
  },
  {
    testcode: "CYTO",
    testname: "Cytology",
    category: "Histopathology",
    unit: "Descriptive",
    agegroup: "ALL",
    sex: "ANY",
    referencetext: "Negative",
    panictext: "Malignant cells",
  },
  {
    testcode: "FISH",
    testname: "Fluorescence In Situ Hybridization",
    category: "Histopathology",
    unit: "Positive/Negative",
    agegroup: "ALL",
    sex: "ANY",
    referencetext: "Negative",
    panictext: "Oncogenic finding",
  },
  {
    testcode: "SEQ",
    testname: "Genetic Sequencing",
    category: "Histopathology",
    unit: "Descriptive",
    agegroup: "ALL",
    sex: "ANY",
    referencetext: "Wild type",
    panictext: "Pathogenic variant",
  },

  // ENDOCRINOLOGY
  {
    testcode: "TSH",
    testname: "Thyroid Stimulating Hormone",
    category: "Endocrinology",
    unit: "mIU/L",
    agegroup: "ADULT",
    sex: "ANY",
    referencemin: 0.4,
    referencemax: 4.5,
    paniclow: 0.01,
    panichigh: 20,
  },
];

async function seedTestReferenceRanges() {
  console.log("Starting test reference ranges seed...");

  try {
    for (const data of testReferenceData) {
      await db.insert(testReferenceRanges).values({
        workspaceid: WORKSPACE_ID,
        testcode: data.testcode,
        testname: data.testname,
        category: data.category,
        unit: data.unit,
        agegroup: data.agegroup,
        sex: data.sex,
        referencemin: data.referencemin?.toString(),
        referencemax: data.referencemax?.toString(),
        referencetext: data.referencetext,
        paniclow: data.paniclow?.toString(),
        panichigh: data.panichigh?.toString(),
        panictext: data.panictext,
        isactive: "Y",
        createdby: CREATED_BY,
      });
    }

    console.log(`✅ Successfully seeded ${testReferenceData.length} test reference ranges`);
  } catch (error) {
    console.error("❌ Error seeding test reference ranges:", error);
    throw error;
  }
}

// Run the seed function
seedTestReferenceRanges()
  .then(() => {
    console.log("Seed completed successfully");
    process.exit(0);
  })
  .catch((error) => {
    console.error("Seed failed:", error);
    process.exit(1);
  });
