curl -X POST "https://base.tibbna.com/ehrbase/rest/openehr/v1/ehr/60fb6d3f-3538-47e6-ab17-91890ce21f75/composition?templateId=clinical_encounter_v1&format=FLAT" \
  -H "X-API-Key: BgMxGMZk5isfCWezE5CF" \
  -H "Authorization: Basic $(echo -n 'auto-speed-ranting:KivLWsQgN4f8aiHAvwuq' | base64)" \
  -H "Content-Type: application/json" \
  -H "Prefer: return=representation" \
  -H "Accept: application/json" \
  -d '{
  "clinical_encounter_v1/category|value" : "event",
  "clinical_encounter_v1/category|terminology" : "openehr",
  "clinical_encounter_v1/category|code" : "433",
  "clinical_encounter_v1/context/start_time" : "2022-02-03T04:05:06",
  "clinical_encounter_v1/context/setting|code" : "225",
  "clinical_encounter_v1/context/setting|terminology" : "openehr",
  "clinical_encounter_v1/context/setting|value" : "home",
  "clinical_encounter_v1/context/_end_time" : "2022-02-03T04:05:06",
  "clinical_encounter_v1/context/_health_care_facility|name" : "DOE, John",
  "clinical_encounter_v1/problem_diagnosis/problem_diagnosis_name" : "Lorem ipsum",
  "clinical_encounter_v1/problem_diagnosis/variant:0" : "Lorem ipsum",
  "clinical_encounter_v1/problem_diagnosis/clinical_description" : "Lorem ipsum",
  "clinical_encounter_v1/problem_diagnosis/body_site:0" : "Lorem ipsum",
  "clinical_encounter_v1/problem_diagnosis/cause:0" : "Lorem ipsum",
  "clinical_encounter_v1/problem_diagnosis/date_time_of_onset" : "2022-02-03T04:05:06",
  "clinical_encounter_v1/problem_diagnosis/date_time_clinically_recognised" : "2022-02-03T04:05:06",
  "clinical_encounter_v1/problem_diagnosis/severity|code" : "at0047",
  "clinical_encounter_v1/problem_diagnosis/severity|terminology" : "local",
  "clinical_encounter_v1/problem_diagnosis/severity|value" : "Mild",
  "clinical_encounter_v1/problem_diagnosis/course_description" : "Lorem ipsum",
  "clinical_encounter_v1/problem_diagnosis/date_time_of_resolution" : "2022-02-03T04:05:06",
  "clinical_encounter_v1/problem_diagnosis/diagnostic_certainty|code" : "at0074",
  "clinical_encounter_v1/problem_diagnosis/diagnostic_certainty|terminology" : "local",
  "clinical_encounter_v1/problem_diagnosis/diagnostic_certainty|value" : "Suspected",
  "clinical_encounter_v1/problem_diagnosis/comment" : "Lorem ipsum",
  "clinical_encounter_v1/problem_diagnosis/last_updated" : "2022-02-03T04:05:06",
  "clinical_encounter_v1/problem_diagnosis/language|code" : "en",
  "clinical_encounter_v1/problem_diagnosis/language|terminology" : "ISO_639-1",
  "clinical_encounter_v1/problem_diagnosis/encoding|terminology" : "IANA_character-sets",
  "clinical_encounter_v1/problem_diagnosis/encoding|code" : "UTF-8",
  "clinical_encounter_v1/problem_diagnosis/_work_flow_id|id" : "a8de3e47-8bbe-35e2-817b-638c788852ec",
  "clinical_encounter_v1/problem_diagnosis/_work_flow_id|id_scheme" : "scheme",
  "clinical_encounter_v1/problem_diagnosis/_work_flow_id|namespace" : "unknown",
  "clinical_encounter_v1/problem_diagnosis/_work_flow_id|type" : "ANY",
  "clinical_encounter_v1/problem_diagnosis/_guideline_id|id" : "a4c2c78a-8ef3-36f8-9f9c-459453a773b5",
  "clinical_encounter_v1/problem_diagnosis/_guideline_id|id_scheme" : "scheme",
  "clinical_encounter_v1/problem_diagnosis/_guideline_id|namespace" : "unknown",
  "clinical_encounter_v1/problem_diagnosis/_guideline_id|type" : "ANY",
  "clinical_encounter_v1/language|code" : "en",
  "clinical_encounter_v1/language|terminology" : "ISO_639-1",
  "clinical_encounter_v1/territory|terminology" : "ISO_3166-1",
  "clinical_encounter_v1/territory|code" : "DE",
  "clinical_encounter_v1/composer|name" : "Max Mustermann"
}'



curl -X POST "https://base.tibbna.com/ehrbase/rest/openehr/v1/ehr/60fb6d3f-3538-47e6-ab17-91890ce21f75/composition?templateId=template_clinical_encounter_v2&format=FLAT" \
  -H "X-API-Key: BgMxGMZk5isfCWezE5CF" \
  -H "Authorization: Basic $(echo -n 'auto-speed-ranting:KivLWsQgN4f8aiHAvwuq' | base64)" \
  -H "Content-Type: application/json" \
  -H "Prefer: return=representation" \
  -H "Accept: application/json" \
  -d '{
  "template_clinical_encounter_v2/category|terminology" : "openehr",
  "template_clinical_encounter_v2/category|code" : "433",
  "template_clinical_encounter_v2/category|value" : "event",
  "template_clinical_encounter_v2/context/start_time" : "2022-02-03T04:05:06",
  "template_clinical_encounter_v2/context/setting|value" : "home",
  "template_clinical_encounter_v2/context/setting|code" : "225",
  "template_clinical_encounter_v2/context/setting|terminology" : "openehr",
  "template_clinical_encounter_v2/context/_end_time" : "2022-02-03T04:05:06",
  "template_clinical_encounter_v2/context/_health_care_facility|name" : "DOE, John",
  "template_clinical_encounter_v2/problem_diagnosis/problem_diagnosis_name" : "Lorem ipsum",
  "template_clinical_encounter_v2/problem_diagnosis/variant:0" : "Lorem ipsum",
  "template_clinical_encounter_v2/problem_diagnosis/clinical_description" : "Lorem ipsum",
  "template_clinical_encounter_v2/problem_diagnosis/body_site:0" : "Lorem ipsum",
  "template_clinical_encounter_v2/problem_diagnosis/cause:0" : "Lorem ipsum",
  "template_clinical_encounter_v2/problem_diagnosis/date_time_of_onset" : "2022-02-03T04:05:06",
  "template_clinical_encounter_v2/problem_diagnosis/date_time_clinically_recognised" : "2022-02-03T04:05:06",
  "template_clinical_encounter_v2/problem_diagnosis/severity|value" : "Mild",
  "template_clinical_encounter_v2/problem_diagnosis/severity|terminology" : "local",
  "template_clinical_encounter_v2/problem_diagnosis/severity|code" : "at0047",
  "template_clinical_encounter_v2/problem_diagnosis/course_description" : "Lorem ipsum",
  "template_clinical_encounter_v2/problem_diagnosis/date_time_of_resolution" : "2022-02-03T04:05:06",
  "template_clinical_encounter_v2/problem_diagnosis/diagnostic_certainty|terminology" : "local",
  "template_clinical_encounter_v2/problem_diagnosis/diagnostic_certainty|code" : "at0074",
  "template_clinical_encounter_v2/problem_diagnosis/diagnostic_certainty|value" : "Suspected",
  "template_clinical_encounter_v2/problem_diagnosis/comment" : "Lorem ipsum",
  "template_clinical_encounter_v2/problem_diagnosis/last_updated" : "2022-02-03T04:05:06",
  "template_clinical_encounter_v2/problem_diagnosis/language|code" : "en",
  "template_clinical_encounter_v2/problem_diagnosis/language|terminology" : "ISO_639-1",
  "template_clinical_encounter_v2/problem_diagnosis/encoding|code" : "UTF-8",
  "template_clinical_encounter_v2/problem_diagnosis/encoding|terminology" : "IANA_character-sets",
  "template_clinical_encounter_v2/problem_diagnosis/_work_flow_id|id" : "a8de3e47-8bbe-35e2-817b-638c788852ec",
  "template_clinical_encounter_v2/problem_diagnosis/_work_flow_id|id_scheme" : "scheme",
  "template_clinical_encounter_v2/problem_diagnosis/_work_flow_id|namespace" : "unknown",
  "template_clinical_encounter_v2/problem_diagnosis/_work_flow_id|type" : "ANY",
  "template_clinical_encounter_v2/problem_diagnosis/_guideline_id|id" : "a4c2c78a-8ef3-36f8-9f9c-459453a773b5",
  "template_clinical_encounter_v2/problem_diagnosis/_guideline_id|id_scheme" : "scheme",
  "template_clinical_encounter_v2/problem_diagnosis/_guideline_id|namespace" : "unknown",
  "template_clinical_encounter_v2/problem_diagnosis/_guideline_id|type" : "ANY",
  "template_clinical_encounter_v2/service_request/request/service_name|other" : "Lorem ipsum",
  "template_clinical_encounter_v2/service_request/request/service_type|terminology" : "local",
  "template_clinical_encounter_v2/service_request/request/service_type|code" : "at0005",
  "template_clinical_encounter_v2/service_request/request/service_type|value" : "Laboratory Test",
  "template_clinical_encounter_v2/service_request/request/description" : "Lorem ipsum",
  "template_clinical_encounter_v2/service_request/request/clinical_indication" : "Lorem ipsum",
  "template_clinical_encounter_v2/service_request/request/urgency|code" : "at0014",
  "template_clinical_encounter_v2/service_request/request/urgency|value" : "Routine",
  "template_clinical_encounter_v2/service_request/request/urgency|terminology" : "local",
  "template_clinical_encounter_v2/service_request/request/requested_date" : "2022-02-03T04:05:06",
  "template_clinical_encounter_v2/service_request/request/requesting_provider" : "Lorem ipsum",
  "template_clinical_encounter_v2/service_request/request/receiving_provider" : "Lorem ipsum",
  "template_clinical_encounter_v2/service_request/request/request_status|terminology" : "local",
  "template_clinical_encounter_v2/service_request/request/request_status|code" : "at0021",
  "template_clinical_encounter_v2/service_request/request/request_status|value" : "Requested",
  "template_clinical_encounter_v2/service_request/request/special_requirements" : "Lorem ipsum",
  "template_clinical_encounter_v2/service_request/request/timing|formalism" : "text/html",
  "template_clinical_encounter_v2/service_request/request/timing" : "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><title>Hello World</title></head><body>Hello World!</body></html>",
  "template_clinical_encounter_v2/service_request/request/action_archetype_id" : "/.*/",
  "template_clinical_encounter_v2/service_request/request_id" : "Lorem ipsum",
  "template_clinical_encounter_v2/service_request/narrative" : "Lorem ipsum",
  "template_clinical_encounter_v2/service_request/language|terminology" : "ISO_639-1",
  "template_clinical_encounter_v2/service_request/language|code" : "en",
  "template_clinical_encounter_v2/service_request/encoding|terminology" : "IANA_character-sets",
  "template_clinical_encounter_v2/service_request/encoding|code" : "UTF-8",
  "template_clinical_encounter_v2/service_request/_work_flow_id|id" : "b6066b93-5aa0-3a3b-aec2-0c14f334ab4c",
  "template_clinical_encounter_v2/service_request/_work_flow_id|id_scheme" : "scheme",
  "template_clinical_encounter_v2/service_request/_work_flow_id|namespace" : "unknown",
  "template_clinical_encounter_v2/service_request/_work_flow_id|type" : "ANY",
  "template_clinical_encounter_v2/service_request/_guideline_id|id" : "31c2cdbd-8dae-3c93-bd8f-fc6c8f824fae",
  "template_clinical_encounter_v2/service_request/_guideline_id|id_scheme" : "scheme",
  "template_clinical_encounter_v2/service_request/_guideline_id|namespace" : "unknown",
  "template_clinical_encounter_v2/service_request/_guideline_id|type" : "ANY",
  "template_clinical_encounter_v2/service_request/_wf_definition|value" : "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><title>Hello World</title></head><body>Hello World!</body></html>",
  "template_clinical_encounter_v2/service_request/_wf_definition|formalism" : "text/html",
  "template_clinical_encounter_v2/medication_order/order:0/medication_item" : "Lorem ipsum",
  "template_clinical_encounter_v2/medication_order/order:0/route:0" : "Lorem ipsum",
  "template_clinical_encounter_v2/medication_order/order:0/body_site" : "Lorem ipsum",
  "template_clinical_encounter_v2/medication_order/order:0/administration_method:0" : "Lorem ipsum",
  "template_clinical_encounter_v2/medication_order/order:0/overall_directions_description" : "Lorem ipsum",
  "template_clinical_encounter_v2/medication_order/order:0/parsable_directions" : "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><title>Hello World</title></head><body>Hello World!</body></html>",
  "template_clinical_encounter_v2/medication_order/order:0/parsable_directions|formalism" : "text/html",
  "template_clinical_encounter_v2/medication_order/order:0/specific_directions_description:0" : "Lorem ipsum",
  "template_clinical_encounter_v2/medication_order/order:0/dosage_justification:0" : "Lorem ipsum",
  "template_clinical_encounter_v2/medication_order/order:0/medication_safety/exceptional_safety_override" : true,
  "template_clinical_encounter_v2/medication_order/order:0/medication_safety/safety_override:0/overriden_safety_advice" : "Lorem ipsum",
  "template_clinical_encounter_v2/medication_order/order:0/medication_safety/safety_override:0/override_reason:0" : "Lorem ipsum",
  "template_clinical_encounter_v2/medication_order/order:0/medication_safety/maximum_dose:0/maximum_amount|unit" : "mm",
  "template_clinical_encounter_v2/medication_order/order:0/medication_safety/maximum_dose:0/maximum_amount|magnitude" : 22.0,
  "template_clinical_encounter_v2/medication_order/order:0/medication_safety/maximum_dose:0/allowed_period" : "PT0S",
  "template_clinical_encounter_v2/medication_order/order:0/medication_safety/total_daily_effective_dose/purpose" : "Lorem ipsum",
  "template_clinical_encounter_v2/medication_order/order:0/medication_safety/total_daily_effective_dose/total_daily_amount|magnitude" : 22.0,
  "template_clinical_encounter_v2/medication_order/order:0/medication_safety/total_daily_effective_dose/total_daily_amount|unit" : "mm",
  "template_clinical_encounter_v2/medication_order/order:0/additional_instruction:0" : "Lorem ipsum",
  "template_clinical_encounter_v2/medication_order/order:0/patient_information:0" : "Lorem ipsum",
  "template_clinical_encounter_v2/medication_order/order:0/monitoring_instruction:0" : "Lorem ipsum",
  "template_clinical_encounter_v2/medication_order/order:0/clinical_indication:0" : "Lorem ipsum",
  "template_clinical_encounter_v2/medication_order/order:0/therapeutic_intent:0" : "Lorem ipsum",
  "template_clinical_encounter_v2/medication_order/order:0/clinician_guidance" : "Lorem ipsum",
  "template_clinical_encounter_v2/medication_order/order:0/order_details/order_start_date_time" : "2022-02-03T04:05:06",
  "template_clinical_encounter_v2/medication_order/order:0/order_details/order_stop_date_time" : "2022-02-03T04:05:06",
  "template_clinical_encounter_v2/medication_order/order:0/order_details/order_start_criterion:0" : "Lorem ipsum",
  "template_clinical_encounter_v2/medication_order/order:0/order_details/order_stop_criterion:0" : "Lorem ipsum",
  "template_clinical_encounter_v2/medication_order/order:0/order_details/administrations_completed" : 21,
  "template_clinical_encounter_v2/medication_order/order:0/order_details/duration_of_order_completed" : "PT0S",
  "template_clinical_encounter_v2/medication_order/order:0/dispense_directions/dispense_instruction:0" : "Lorem ipsum",
  "template_clinical_encounter_v2/medication_order/order:0/dispense_directions/substitution_direction|value" : "Permitted",
  "template_clinical_encounter_v2/medication_order/order:0/dispense_directions/substitution_direction|code" : "at0168",
  "template_clinical_encounter_v2/medication_order/order:0/dispense_directions/substitution_direction|terminology" : "local",
  "template_clinical_encounter_v2/medication_order/order:0/dispense_directions/non-substitution_reason" : "Lorem ipsum",
  "template_clinical_encounter_v2/medication_order/order:0/dispense_directions/priority" : "Lorem ipsum",
  "template_clinical_encounter_v2/medication_order/order:0/dispense_directions/dispensing_start_date" : "2022-02-03T04:05:06",
  "template_clinical_encounter_v2/medication_order/order:0/dispense_directions/dispensing_expiry_date" : "2022-02-03T04:05:06",
  "template_clinical_encounter_v2/medication_order/order:0/comment" : "Lorem ipsum",
  "template_clinical_encounter_v2/medication_order/order:0/timing|formalism" : "text/html",
  "template_clinical_encounter_v2/medication_order/order:0/timing" : "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><title>Hello World</title></head><body>Hello World!</body></html>",
  "template_clinical_encounter_v2/medication_order/order:0/action_archetype_id" : "/.*/",
  "template_clinical_encounter_v2/medication_order/order_identifier:0|id" : "dev/null",
  "template_clinical_encounter_v2/medication_order/narrative" : "Lorem ipsum",
  "template_clinical_encounter_v2/medication_order/language|terminology" : "ISO_639-1",
  "template_clinical_encounter_v2/medication_order/language|code" : "en",
  "template_clinical_encounter_v2/medication_order/encoding|terminology" : "IANA_character-sets",
  "template_clinical_encounter_v2/medication_order/encoding|code" : "UTF-8",
  "template_clinical_encounter_v2/medication_order/_work_flow_id|id" : "3db43522-c1bf-34fe-9a03-b063ae37cdb7",
  "template_clinical_encounter_v2/medication_order/_work_flow_id|id_scheme" : "scheme",
  "template_clinical_encounter_v2/medication_order/_work_flow_id|namespace" : "unknown",
  "template_clinical_encounter_v2/medication_order/_work_flow_id|type" : "ANY",
  "template_clinical_encounter_v2/medication_order/_guideline_id|id" : "a217d528-787b-3c0f-9e95-53d8c09dc303",
  "template_clinical_encounter_v2/medication_order/_guideline_id|id_scheme" : "scheme",
  "template_clinical_encounter_v2/medication_order/_guideline_id|namespace" : "unknown",
  "template_clinical_encounter_v2/medication_order/_guideline_id|type" : "ANY",
  "template_clinical_encounter_v2/medication_order/_wf_definition|value" : "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><title>Hello World</title></head><body>Hello World!</body></html>",
  "template_clinical_encounter_v2/medication_order/_wf_definition|formalism" : "text/html",
  "template_clinical_encounter_v2/vital_signs/any_event:0/systolic_blood_pressure|magnitude" : 150.0,
  "template_clinical_encounter_v2/vital_signs/any_event:0/systolic_blood_pressure|unit" : "mm[Hg]",
  "template_clinical_encounter_v2/vital_signs/any_event:0/diastolic_blood_pressure|unit" : "mm[Hg]",
  "template_clinical_encounter_v2/vital_signs/any_event:0/diastolic_blood_pressure|magnitude" : 100.0,
  "template_clinical_encounter_v2/vital_signs/any_event:0/heart_rate|unit" : "/min",
  "template_clinical_encounter_v2/vital_signs/any_event:0/heart_rate|magnitude" : 150.0,
  "template_clinical_encounter_v2/vital_signs/any_event:0/body_temperature|magnitude" : 38.0,
  "template_clinical_encounter_v2/vital_signs/any_event:0/body_temperature|unit" : "°C",
  "template_clinical_encounter_v2/vital_signs/any_event:0/respiratory_rate|magnitude" : 50.0,
  "template_clinical_encounter_v2/vital_signs/any_event:0/respiratory_rate|unit" : "/min",
  "template_clinical_encounter_v2/vital_signs/any_event:0/oxygen_saturation_spo2|unit" : "%",
  "template_clinical_encounter_v2/vital_signs/any_event:0/oxygen_saturation_spo2|magnitude" : 50.0,
  "template_clinical_encounter_v2/vital_signs/any_event:0/comments" : "Lorem ipsum",
  "template_clinical_encounter_v2/vital_signs/any_event:0/position|terminology" : "local",
  "template_clinical_encounter_v2/vital_signs/any_event:0/position|value" : "Lying",
  "template_clinical_encounter_v2/vital_signs/any_event:0/position|code" : "at0013",
  "template_clinical_encounter_v2/vital_signs/any_event:0/time" : "2022-02-03T04:05:06",
  "template_clinical_encounter_v2/vital_signs/any_event:0/width" : "PT42H",
  "template_clinical_encounter_v2/vital_signs/any_event:0/math_function|code" : "145",
  "template_clinical_encounter_v2/vital_signs/any_event:0/math_function|terminology" : "openehr",
  "template_clinical_encounter_v2/vital_signs/any_event:0/math_function|value" : "minimum",
  "template_clinical_encounter_v2/vital_signs/any_event:1/systolic_blood_pressure|magnitude" : 150.0,
  "template_clinical_encounter_v2/vital_signs/any_event:1/systolic_blood_pressure|unit" : "mm[Hg]",
  "template_clinical_encounter_v2/vital_signs/any_event:1/diastolic_blood_pressure|magnitude" : 100.0,
  "template_clinical_encounter_v2/vital_signs/any_event:1/diastolic_blood_pressure|unit" : "mm[Hg]",
  "template_clinical_encounter_v2/vital_signs/any_event:1/heart_rate|magnitude" : 150.0,
  "template_clinical_encounter_v2/vital_signs/any_event:1/heart_rate|unit" : "/min",
  "template_clinical_encounter_v2/vital_signs/any_event:1/body_temperature|magnitude" : 38.0,
  "template_clinical_encounter_v2/vital_signs/any_event:1/body_temperature|unit" : "°C",
  "template_clinical_encounter_v2/vital_signs/any_event:1/respiratory_rate|unit" : "/min",
  "template_clinical_encounter_v2/vital_signs/any_event:1/respiratory_rate|magnitude" : 50.0,
  "template_clinical_encounter_v2/vital_signs/any_event:1/oxygen_saturation_spo2|unit" : "%",
  "template_clinical_encounter_v2/vital_signs/any_event:1/oxygen_saturation_spo2|magnitude" : 50.0,
  "template_clinical_encounter_v2/vital_signs/any_event:1/comments" : "Lorem ipsum",
  "template_clinical_encounter_v2/vital_signs/any_event:1/position|code" : "at0013",
  "template_clinical_encounter_v2/vital_signs/any_event:1/position|terminology" : "local",
  "template_clinical_encounter_v2/vital_signs/any_event:1/position|value" : "Lying",
  "template_clinical_encounter_v2/vital_signs/any_event:1/time" : "2022-02-03T04:05:06",
  "template_clinical_encounter_v2/vital_signs/any_event:2/systolic_blood_pressure|unit" : "mm[Hg]",
  "template_clinical_encounter_v2/vital_signs/any_event:2/systolic_blood_pressure|magnitude" : 150.0,
  "template_clinical_encounter_v2/vital_signs/any_event:2/diastolic_blood_pressure|unit" : "mm[Hg]",
  "template_clinical_encounter_v2/vital_signs/any_event:2/diastolic_blood_pressure|magnitude" : 100.0,
  "template_clinical_encounter_v2/vital_signs/any_event:2/heart_rate|unit" : "/min",
  "template_clinical_encounter_v2/vital_signs/any_event:2/heart_rate|magnitude" : 150.0,
  "template_clinical_encounter_v2/vital_signs/any_event:2/body_temperature|unit" : "°C",
  "template_clinical_encounter_v2/vital_signs/any_event:2/body_temperature|magnitude" : 38.0,
  "template_clinical_encounter_v2/vital_signs/any_event:2/respiratory_rate|unit" : "/min",
  "template_clinical_encounter_v2/vital_signs/any_event:2/respiratory_rate|magnitude" : 50.0,
  "template_clinical_encounter_v2/vital_signs/any_event:2/oxygen_saturation_spo2|unit" : "%",
  "template_clinical_encounter_v2/vital_signs/any_event:2/oxygen_saturation_spo2|magnitude" : 50.0,
  "template_clinical_encounter_v2/vital_signs/any_event:2/comments" : "Lorem ipsum",
  "template_clinical_encounter_v2/vital_signs/any_event:2/position|terminology" : "local",
  "template_clinical_encounter_v2/vital_signs/any_event:2/position|value" : "Lying",
  "template_clinical_encounter_v2/vital_signs/any_event:2/position|code" : "at0013",
  "template_clinical_encounter_v2/vital_signs/any_event:2/time" : "2022-02-03T04:05:06",
  "template_clinical_encounter_v2/vital_signs/any_event:2/width" : "PT42H",
  "template_clinical_encounter_v2/vital_signs/any_event:2/math_function|value" : "minimum",
  "template_clinical_encounter_v2/vital_signs/any_event:2/math_function|code" : "145",
  "template_clinical_encounter_v2/vital_signs/any_event:2/math_function|terminology" : "openehr",
  "template_clinical_encounter_v2/vital_signs/device" : "Lorem ipsum",
  "template_clinical_encounter_v2/vital_signs/language|terminology" : "ISO_639-1",
  "template_clinical_encounter_v2/vital_signs/language|code" : "en",
  "template_clinical_encounter_v2/vital_signs/encoding|code" : "UTF-8",
  "template_clinical_encounter_v2/vital_signs/encoding|terminology" : "IANA_character-sets",
  "template_clinical_encounter_v2/vital_signs/_work_flow_id|id" : "13471138-b7d8-3c26-a775-b11ccc262922",
  "template_clinical_encounter_v2/vital_signs/_work_flow_id|id_scheme" : "scheme",
  "template_clinical_encounter_v2/vital_signs/_work_flow_id|namespace" : "unknown",
  "template_clinical_encounter_v2/vital_signs/_work_flow_id|type" : "ANY",
  "template_clinical_encounter_v2/vital_signs/_guideline_id|id" : "b68c17b0-ba91-3a65-b82e-a12c5b65666e",
  "template_clinical_encounter_v2/vital_signs/_guideline_id|id_scheme" : "scheme",
  "template_clinical_encounter_v2/vital_signs/_guideline_id|namespace" : "unknown",
  "template_clinical_encounter_v2/vital_signs/_guideline_id|type" : "ANY",
  "template_clinical_encounter_v2/language|code" : "en",
  "template_clinical_encounter_v2/language|terminology" : "ISO_639-1",
  "template_clinical_encounter_v2/territory|terminology" : "ISO_3166-1",
  "template_clinical_encounter_v2/territory|code" : "DE",
  "template_clinical_encounter_v2/composer|name" : "Max Mustermann"
}'



