/* prettier-ignore */
export const enTranslations = {
  'ServiceName': 'Tibbna',
  'Settings': 'Settings',
  'Projects': 'Projects',
  'Teams': 'Teams',
  'Add team': 'Add team',
  'Account Settings': 'Account Settings',
  'Log out': 'Log out',
  'More': 'More',
  'View Project': 'View Project',
  'Share Project': 'Share Project',
  'Delete Project': 'Delete Project',
  'Dashboard': 'Dashboard',
  'Profile': 'Profile',
  'Users': 'Users',
  'Page 1': 'Page 1',
  'Page 2': 'Page 2',
  'Failed to sign in with Google. Please try again.': 'Failed to sign in with Google. Please try again.',
  'Invalid email or password. Please check your credentials and try again.': 'Invalid email or password. Please check your credentials and try again.',
  'An error occurred during sign in. Please try again.': 'An error occurred during sign in. Please try again.',
  'An unexpected error occurred. Please try again.': 'An unexpected error occurred. Please try again.',
  'Network error. Please check your connection and try again.': 'Network error. Please check your connection and try again.',
  'Welcome back': 'Welcome back',
  'Login with your Google account or email and password': 'Login with your Google account or email and password',
  'Login with Google': 'Login with Google',
  'Or continue with': 'Or continue with',
  'Email': 'Email',
  'Password': 'Password',
  'Forgot your password?': 'Forgot your password?',
  'Signing in...': 'Signing in...',
  'Login': 'Login',
  'Sign up': 'Sign up',
  'Don\'t have an account?': 'Don\'t have an account?',
  'Help': 'Help',
  'Create Workspace': 'Create Workspace',
  'Workspace': 'Workspace',
  'Workspaces': 'Workspaces',
  'Schedule': 'Schedule',
  'Patients': 'Patients',
  'Patient List': 'Patient List',
  'New Patient': 'New Patient',
  'Search Patient': 'Search Patient',
  'Medical Records': 'Medical Records',
  'View Records': 'View Records',
  'Create Record': 'Create Record',
  'Lab Results': 'Lab Results',
  'Prescriptions': 'Prescriptions',
  'Write Prescription': 'Write Prescription',
  'Prescription History': 'Prescription History',
  'Drug Database': 'Drug Database',
  'Diagnostics': 'Diagnostics',
  'Order Tests': 'Order Tests',
  'View Results': 'View Results',
  'Imaging': 'Imaging',
  'Vital Signs': 'Vital Signs',
  'Medication Admin': 'Medication Admin',
  'Care Plans': 'Care Plans',
  'Active Plans': 'Active Plans',
  'Create Plan': 'Create Plan',
  'Progress Notes': 'Progress Notes',
  'Monitoring': 'Monitoring',
  'Patient Monitoring': 'Patient Monitoring',
  'Alerts': 'Alerts',
  'Rounds': 'Rounds',
  'Appointments': 'Appointments',
  'Today\'s Appointments': 'Today\'s Appointments',
  'Schedule Appointment': 'Schedule Appointment',
  'Calendar View': 'Calendar View',
  'Patient Registration': 'Patient Registration',
  'Check-in': 'Check-in',
  'Billing': 'Billing',
  'Generate Invoice': 'Generate Invoice',
  'Payment Processing': 'Payment Processing',
  'Insurance Claims': 'Insurance Claims',
  'Reports': 'Reports',
  'Daily Reports': 'Daily Reports',
  'Patient Flow': 'Patient Flow',
  'Revenue Reports': 'Revenue Reports',
  'Staff Management': 'Staff Management',
  'Staff List': 'Staff List',
  'Schedules': 'Schedules',
  'Roles & Permissions': 'Roles & Permissions',
  'Department Management': 'Department Management',
  'Departments': 'Departments',
  'Resources': 'Resources',
  'Capacity Planning': 'Capacity Planning',
  'Reports & Analytics': 'Reports & Analytics',
  'Performance Metrics': 'Performance Metrics',
  'Financial Reports': 'Financial Reports',
  'Quality Metrics': 'Quality Metrics',
  'Admin Panel': 'Admin Panel',
  'Lab Orders': 'Lab Orders',
  'Pending Orders': 'Pending Orders',
  'In Progress': 'In Progress',
  'Completed': 'Completed',
  'Results Review': 'Results Review',
  'Pending Review': 'Pending Review',
  'Approved Results': 'Approved Results',
  'Critical Values': 'Critical Values',
  'Quality Control': 'Quality Control',
  'QC Results': 'QC Results',
  'Calibration': 'Calibration',
  'Maintenance': 'Maintenance',
  'Sample Collection': 'Sample Collection',
  'Collection Schedule': 'Collection Schedule',
  'Sample Tracking': 'Sample Tracking',
  'Collection Guidelines': 'Collection Guidelines',
  'Patient Preparation': 'Patient Preparation',
  'Pre-test Instructions': 'Pre-test Instructions',
  'Patient Education': 'Patient Education',
  'Consent Forms': 'Consent Forms',
  'Patient Communication': 'Patient Communication',
  'Lab Appointments': 'Lab Appointments',
  'Walk-in Queue': 'Walk-in Queue',
  'Sample Drop-off': 'Sample Drop-off',
  'Register Patient': 'Register Patient',
  'Update Information': 'Update Information',
  'Insurance Verification': 'Insurance Verification',
  'Billing & Reports': 'Billing & Reports',
  'Test Billing': 'Test Billing',
  'Lab Management': 'Lab Management',
  'Equipment Status': 'Equipment Status',
  'Inventory': 'Inventory',
  'Workflow Optimization': 'Workflow Optimization',
  'Staff & Scheduling': 'Staff & Scheduling',
  'Shift Scheduling': 'Shift Scheduling',
  'Competency Tracking': 'Competency Tracking',
  'Analytics': 'Analytics',
  'Turnaround Times': 'Turnaround Times',
  'Test Volume': 'Test Volume',
  'Prescription Review': 'Prescription Review',
  'Drug Interactions': 'Drug Interactions',
  'Clinical Guidelines': 'Clinical Guidelines',
  'Patient Consultation': 'Patient Consultation',
  'Medication Counseling': 'Medication Counseling',
  'Therapy Management': 'Therapy Management',
  'Adverse Events': 'Adverse Events',
  'Drug Information': 'Drug Information',
  'Formulary': 'Formulary',
  'Clinical Studies': 'Clinical Studies',
  'Medication Administration': 'Medication Administration',
  'Patient Medications': 'Patient Medications',
  'Administration Records': 'Administration Records',
  'Medication Reconciliation': 'Medication Reconciliation',
  'Medication Instructions': 'Medication Instructions',
  'Side Effects': 'Side Effects',
  'Compliance Monitoring': 'Compliance Monitoring',
  'Inventory Support': 'Inventory Support',
  'Stock Levels': 'Stock Levels',
  'Expiry Tracking': 'Expiry Tracking',
  'Prescription Processing': 'Prescription Processing',
  'New Prescriptions': 'New Prescriptions',
  'Refills': 'Refills',
  'Customer Service': 'Customer Service',
  'Customer Registration': 'Customer Registration',
  'Pickup Notifications': 'Pickup Notifications',
  'Sales & Billing': 'Sales & Billing',
  'Point of Sale': 'Point of Sale',
  'Pharmacy Operations': 'Pharmacy Operations',
  'Inventory Management': 'Inventory Management',
  'Supplier Relations': 'Supplier Relations',
  'Pharmacist Scheduling': 'Pharmacist Scheduling',
  'Technician Management': 'Technician Management',
  'Training Records': 'Training Records',
  'Business Analytics': 'Business Analytics',
  'Sales Analytics': 'Sales Analytics',
  'Prescription Trends': 'Prescription Trends',
  'All Appointments': 'All Appointments',
  'Patient Records': 'Patient Records',
  'Physicians': 'Physicians',
  'Physician List': 'Physician List',
  'Add Physician': 'Add Physician',
  'Performance': 'Performance',
  'Orders': 'Orders',
  'Suppliers': 'Suppliers',
  'Lab': 'Lab',
  'Lab Tests': 'Lab Tests',
  'Results': 'Results',
  'Equipment': 'Equipment',
  'Department': 'Department',
  'All Departments': 'All Departments',
  'Add Department': 'Add Department',
  'Staff Assignment': 'Staff Assignment',
  'Insurance': 'Insurance',
  'Insurance Plans': 'Insurance Plans',
  'Claims': 'Claims',
  'Verification': 'Verification',
  'Providers': 'Providers',
  'Invoices': 'Invoices',
  'Payments': 'Payments',
  'Outstanding': 'Outstanding',
  'Hospital': 'Hospital',
  'Laboratory': 'Laboratory',
  'Pharmacy': 'Pharmacy',
  'Theme': 'Theme',
  'Choose your preferred theme appearance': 'Choose your preferred theme appearance',
  'Language': 'Language',
  'Select your preferred language': 'Select your preferred language',
  'Your account is not connected to any workspaces': 'Your account is not connected to any workspaces',
  'Please contact your administrator or support team': 'Please contact your administrator or support team',
  'No email address provided. Please try again with a valid email.': 'No email address provided. Please try again with a valid email.',
  'User not found. Please contact your administrator to create an account.': 'User not found. Please contact your administrator to create an account.',
  'Compositions': 'Compositions',
  'EHR ID': 'EHR ID',
  'Add Encounter': 'Add Encounter',
  'Failed to create encounter': 'Failed to create encounter',
  'Unknown error': 'Unknown error',
  'Create a new clinical encounter for this EHR': 'Create a new clinical encounter for this EHR',
  'Basic Information': 'Basic Information',
  'Composer Name': 'Composer Name',
  'Enter composer name': 'Enter composer name',
  'Facility Name': 'Facility Name',
  'Enter facility name': 'Enter facility name',
  'Start Time': 'Start Time',
  'Diagnosis': 'Diagnosis',
  'Diagnosis Name': 'Diagnosis Name',
  'Enter diagnosis name': 'Enter diagnosis name',
  'Clinical Description': 'Clinical Description',
  'Enter clinical description': 'Enter clinical description',
  'Systolic BP': 'Systolic BP',
  'Diastolic BP': 'Diastolic BP',
  'Heart Rate': 'Heart Rate',
  'Body Temperature': 'Body Temperature',
  'Respiratory Rate': 'Respiratory Rate',
  'SpO2': 'SpO2',
  'Nurses': 'Nurses',
  'Nurse List': 'Nurse List',
  'Add Staff': 'Add Staff',
  'Edit Staff': 'Edit Staff',
  'Staff Details': 'Staff Details',
  'Department List': 'Department List',
  'Edit Department': 'Edit Department',
  'Department Details': 'Department Details',
  'Operations': 'Operations',
  'Operation List': 'Operation List',
  'Schedule Operation': 'Schedule Operation',
  'Operation Details': 'Operation Details',
  'Facilities': 'Facilities',
  'Facility Management': 'Facility Management',
  'Add Facility': 'Add Facility',
  'Edit Facility': 'Edit Facility',
  'Facility Details': 'Facility Details',
  'Cancel': 'Cancel',
  'Create Encounter': 'Create Encounter',
  'Add Lab Report': 'Add Lab Report',
  'Failed to create lab report': 'Failed to create lab report',
  'Add Laboratory Report': 'Add Laboratory Report',
  'Create a new laboratory report for this EHR': 'Create a new laboratory report for this EHR',
  'Enter laboratory name': 'Enter laboratory name',
  'Report ID': 'Report ID',
  'Enter report ID': 'Enter report ID',
  'Report Time': 'Report Time',
  'Test Method': 'Test Method',
  'Enter test method': 'Enter test method',
  'Specimen Type': 'Specimen Type',
  'e.g., Venous blood': 'e.g., Venous blood',
  'Test Events': 'Test Events',
  'Add Test': 'Add Test',
  'Test': 'Test',
  'Test Name': 'Test Name',
  'e.g., Complete Blood Count': 'e.g., Complete Blood Count',
  'Test Status': 'Test Status',
  'Select status': 'Select status',
  'Overall Interpretation': 'Overall Interpretation',
  'Enter overall interpretation': 'Enter overall interpretation',
  'Test Results': 'Test Results',
  'Add Result': 'Add Result',
  'Result Name': 'Result Name',
  'e.g., Hemoglobin': 'e.g., Hemoglobin',
  'Value': 'Value',
  'Unit': 'Unit',
  'Interpretation': 'Interpretation',
  'Reference Range': 'Reference Range',
  'Create Report': 'Create Report'} as const;

export default enTranslations;
