export const enTranslations = {
  'ServiceName': 'IQMED',
  'Settings': 'Settings',
  'Projects': 'Projects',
  'Teams': 'Teams',
  'Add team': 'Add team',
  'Account Settings': 'Account Settings',
  'Log out': 'Log out',
  'More': 'More',
  'View Project': 'View Project',
  'Share Project': 'Share Project',
  'Delete Project': 'Delete Project',
  'Dashboard': 'Dashboard',
  'Profile': 'Profile',
  'Users': 'Users',
  'Page 1': 'Page 1',
  'Page 2': 'Page 2',
  'Failed to sign in with Google. Please try again.': 'Failed to sign in with Google. Please try again.',
  'Invalid email or password. Please check your credentials and try again.': 'Invalid email or password. Please check your credentials and try again.',
  'An error occurred during sign in. Please try again.': 'An error occurred during sign in. Please try again.',
  'An unexpected error occurred. Please try again.': 'An unexpected error occurred. Please try again.',
  'Network error. Please check your connection and try again.': 'Network error. Please check your connection and try again.',
  'Welcome back': 'Welcome back',
  'Login with your Google account or email and password': 'Login with your Google account or email and password',
  'Login with Google': 'Login with Google',
  'Or continue with': 'Or continue with',
  'Email': 'Email',
  'Password': 'Password',
  'Forgot your password?': 'Forgot your password?',
  'Signing in...': 'Signing in...',
  'Login': 'Login',
  'Sign up': 'Sign up',
  'Don\'t have an account?': 'Don\'t have an account?',
  'How do I optimize my company\'s tax situation?': 'How do I optimize my company\'s tax situation?',
  'My transactions': 'My transactions',
  'Invoices': 'Invoices',
  'Offers': 'Offers',
  'Customers': 'Customers',
  'Salaries': 'Salaries',
  'Employees': 'Employees',
  'Outlays': 'Outlays',
  'Help': 'Help',
  'Users who have been invited but haven\'t accepted yet': 'Users who have been invited but haven\'t accepted yet',
  'Please type \'delete\' to confirm': 'Please type \'delete\' to confirm',
  'Type \'delete\' here': 'Type \'delete\' here',
  'Information about your company\'s annual reporting status': 'Information about your company\'s annual reporting status',
  'Choose the plan that\'s right for you.': 'Choose the plan that\'s right for you.',
  'We\'ll sit on your desk.': 'We\'ll sit on your desk.',
  'Don\'t worry! You can still': 'Don\'t worry! You can still',
  'Upgrade later when you\'re ready': 'Upgrade later when you\'re ready',
  'Manage your company\'s subscription and billing': 'Manage your company\'s subscription and billing',
  'Your company\'s current subscription plan': 'Your company\'s current subscription plan',
  'Update your workspace\'s basic information.': 'Update your workspace\'s basic information.',
  'Update your workspace\'s contact information.': 'Update your workspace\'s contact information.',
  'Configure your workspace\'s accounting preferences.': 'Configure your workspace\'s accounting preferences.',
  'Workspace name doesn\'t match': 'Workspace name doesn\'t match',
  'Your workspace\'s current subscription plan': 'Your workspace\'s current subscription plan',
  'Create Workspace': 'Create Workspace',
  'Workspace': 'Workspace',
  'Workspaces': 'Workspaces',
  'Your account is not connected to any workspaces': 'Your account is not connected to any workspaces',
  'Please contact your administrator or support team': 'Please contact your administrator or support team',
  'No email address provided. Please try again with a valid email.': 'No email address provided. Please try again with a valid email.',
  'User not found. Please contact your administrator to create an account.': 'User not found. Please contact your administrator to create an account.'} as const;

export default enTranslations;
